server:
  port: 9000
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/document_management
    username: root
    password: 1q2w3e4r5t
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop #create-drop will throw a CommandAcceptanceException
    database: mysql
    show-sql: true





#logging:
#  level:
#    org:
#      springframework: debug

