server:
  port: 8000
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/document_management
    username: postgres
    password: 134679
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # update
    show-sql: true
    database: postgresql
  main:
    web-application-type: servlet # servlet by default
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB

project:
  bucket: myprettystorage

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

logging:
  level:
    org:
      springframework: debug

